### PR TITLE
If this from a legacy WordPress enclosure, ensure that we are getting…

### PR DESCRIPTION
**Pull request by whyisjake**
… the correct URL.

Was seeing a response like this, and then throwing header errors.
```
http://sunstonemagazine.com/audio/SL15133.mp3
27371505
audio/mpeg
```

### CODE REVIEW

**Comment by whyisjake** [comment]
Might need a little more sanity checks around the file URL.

**Comment by hlashbrooke** [comment]
I haven't encountered this issue myself, but this looks like a fine solution. Should we not also be deleting `$file = $this->get_enclosure( $episode_id );` from line 890 though? It seems like the same function is called twice as it stands right now.

**Comment by whyisjake** [comment]
@hlashbrooke I had some reason for this, but I am failing to remember now. I'll update the PR.

**Comment by hlashbrooke** [comment]
@whyisjake Are you going to update the PR, or can I merge this and edit it myself? I'd rather have it all in one PR as it's easier to track changes and such that way.

**Comment by whyisjake** [comment]
Sorry, long holiday weekend here in the US. I can update.

**Comment by hlashbrooke** [comment]
Perfection - thanks @whyisjake!

**Pull request merged**
