### PR TITLE
Let's add a class for CLI.

### PR DESCRIPTION
**Pull request by whyisjake**
This is just a rough framework that we can use to get started.

### CODE REVIEW

**Comment by hlashbrooke** [comment]
This looks rad - I need to test it out still, but the code looks solid and seeing as though you used it I'm sure it all works as advertised.

I was thinking it would be good to create an extension that handled all the different types of importing, so this code would be in an extension with a UI for supplying the RSS feed to import as well as the CLI function to do it that way. Then, in the future, we could add import options for moving content from other podcasting plugins or from CSV files or anything else we can think of really.

If it's OK with you, could I take this code and put it in a stand alone plugin to release as an extension? For now the changes I would make would be to abstract the import code into helper functions so it could be accessed via CLI or anything else, then create a basic UI for importing an RSS feed. Then down the line, I would look at adding the other import options, but I think adding from RSS is the most critical (and universally relevant).

**Comment by whyisjake** [comment]
Yeah, that sounds good.

**Comment by hlashbrooke** [comment]
Great - I'll get on that and will paste the repo link in here once it's up.

I'm going to close this PR now then, but will leave the branch open so the code is here for now.

**Comment by jacobo** [comment]
hey guys, please pardon my ignorance, did this ever get anywhere? Do you think this code might work with the latest version of seriouslysimplepodcasting? Can you give me a quick rundown of how to use it? I'm familiar with git and the command line (and Ruby), but I'm a total wordpress n00b. thanks @whyisjake @hlashbrooke

**Comment by whyisjake** [comment]
@jacobo If you have wp-cli running, you can checkout this branch, and then run an import with this:

`wp ssp <feed> <slug> <author> <category-slug>`

So, you could do this:

`wp ssp https://www.wired.com/feed/podcast/monitor monitor whyisjake culture`

**Pull request closed without merging**
