### PR TITLE
Ensure the var is set.

### PR DESCRIPTION
**Pull request by whyisjake**
Can throw notices.

### CODE REVIEW

**Comment by hlashbrooke** [comment]
Surely the operator here should be `||` not `&&`? Or am I misreading?

**Comment by hlashbrooke** [comment]
I added a commit to this branch instead of `master` by mistake, but just reverted it, so you can ignore those commits.

**Comment by hlashbrooke** [comment]
I updated this with the `||` operator and further refined the check to prevent errors.

**Comment by whyisjake** [comment]
:+1: :+1:

**Pull request merged**
